const barcelona = {
    title: 'Descubre Barcelona: La joya de Cataluña',
    price : 'Promotion price of: $400',
    subtitle: 'Sumérgete en la historia, cultura y belleza de esta vibrante ciudad',
    paragraph: "Bienvenidos a Barcelona, una ciudad cautivadora que combina a la perfección la riqueza histórica con una atmósfera moderna y dinámica. Situada en la región de Cataluña, al noreste de España, Barcelona es conocida por su arquitectura icónica, su vibrante escena artística, su deliciosa gastronomía y sus hermosas playas mediterráneas. <br> <br> Nuestro recorrido por Barcelona comienza en su corazón histórico: el Barrio Gótico.Perdiéndote en sus estrechas calles empedradas, descubrirás impresionantes edificios medievales, iglesias antiguas y encantadoras plazas llenas de vida.No puedes dejar de visitar la majestuosa Catedral de Barcelona, un magnífico ejemplo de la arquitectura gótica.<br> <br> A medida que te adentras en la ciudad, te maravillarás con las obras maestras arquitectónicas de Antoni Gaudí, uno de los más grandes exponentes del modernismo catalán.La Sagrada Familia, su obra maestra inacabada, te dejará sin palabras con su diseño único y sus detalles ornamentales.Otros tesoros de Gaudí incluyen el Parque Güell, con sus coloridos mosaicos y vistas panorámicas de la ciudad, y la Casa Batlló, un edificio modernista que parece salido de un cuento de hadas.<br> <br> Barcelona también es famosa por su pasión por el fútbol.Si eres amante de este deporte, no puedes perderte el Camp Nou, el estadio del FC Barcelona.Sumérgete en la atmósfera apasionada de un partido y descubre la historia del club en su museo.<br> <br> Pero Barcelona no se trata solo de arquitectura y deporte.La ciudad cuenta con una escena cultural bulliciosa, con una gran variedad de museos, galerías de arte y eventos culturales.El Museo Picasso alberga una impresionante colección de obras del famoso pintor español, mientras que el MACBA y el CCCB son espacios dedicados al arte contemporáneo y la cultura urbana.<br> <br> Cuando necesites un descanso, dirígete a las playas de Barcelona.Relájate bajo el sol mediterráneo, disfruta de un refrescante baño en el mar y prueba las delicias locales en los chiringuitos de playa. <br> <br> Barcelona también es conocida por su animada vida nocturna.Desde bares tradicionales y tabernas hasta clubes nocturnos y discotecas de renombre mundial, la ciudad ofrece opciones para todos los gustos.Pasea por las calles del animado barrio de El Born o disfruta de una copa en los bares de la playa.<br> <br> En resumen, Barcelona es una ciudad fascinante que ofrece una combinación perfecta de historia, cultura, arquitectura y entretenimiento.Prepárate para perderse en sus encantos, saborear su gastronomía, disfrutar de su energía y llevarte recuerdos inolvidables. ¡Descubre Barcelona y déjate cautivar por su magia!"
}

const roma = {
    title: 'Rome: Eternal Treasures in the Eternal City',
    price : 'Promotional price of: $400',
    subtitle: 'Immerse yourself in the historical grandeur, art and culture of the Italian capital',
    paragraph: "Welcome to Rome, a city that breathes history and that will transport you through the centuries. Known as the Eternal City, Rome is home to an unrivaled wealth of ancient monuments, Renaissance art, and a vibrant culture that will captivate you from the very first moment. <br> <br> Our journey through Rome begins in the heart of ancient Rome: the Colosseum. This imposing amphitheater is one of the most iconic architectural wonders in the world and will take your breath away with its magnificence. Imagine the thrilling gladiatorial combats and theatrical performances that once took place in this legendary location.<br> <br> Just steps from the Colosseum, you'll discover the Roman Forum, the political and social center of ancient Rome. Walk through the ruins of ancient temples, triumphal arches and basilicas, and let yourself be carried away by the majesty of this place steeped in history. <br> <br> Continuing our tour, we headed to the Vatican, the smallest independent enclave in the world and the spiritual heart of Catholicism. St. Peter's Basilica, with its iconic dome designed by Michelangelo, will impress you with its beauty and splendor. Don't forget to also visit the Vatican Museums, where you can admire an impressive collection of art, including the famous Sistine Chapel, with its frescoes created by great Renaissance artists.<br> <br> Rome is also known for its enchanting piazzas and fountains. Piazza Navona, with its Baroque architecture and its famous Fountain of the Four Rivers, invites you to relax and enjoy the Roman atmosphere. The Trevi Fountain, the city's most famous fountain, is a must-see place to toss a coin and make sure you return to Rome in the future.<br> <br> Strolling through the cobbled streets of Trastevere will immerse you in the authentic roman life Discover its charming piazzas, colorful facades, and lively bars and restaurants, where you can sample delicious Italian cuisine.<br> <br> Rome is also famous for its catacombs, vast underground systems of tunnels, and burial chambers. Explore the Catacombs of Saint Callixtus or the Catacombs of Saint Sebastian and discover this fascinating legacy of ancient Rome.<br> <br> In short, Rome is a city that will transport you back in time and immerse you in an unparalleled wealth of history , art and culture. From its ancient monuments to its enchanting squares and delicious cuisine, every corner of Rome has a story to tell. Prepare to marvel at the grandeur of the Eternal City and be captivated by its timeless charm."
}

const paris = {
    title: 'Paris: The City of Light and Romance',
    price : 'Promotional price of: $500',
    subtitle: 'Explore the elegance, culture and charm of the French capital',
    paragraph: "Welcome to Paris, a city that has captivated visitors from around the world with its beauty, elegance and romance. Known as the City of Light, Paris offers a unique mix of history, art, culture and gastronomy that makes it a truly unforgettable destination. <br> <br> Our journey through Paris begins in the heart of the city, at the iconic Eiffel Tower. This emblematic structure, built for the Universal Exposition of 1889, will give you an impressive panoramic view of the city. Whether you decide to climb to the top or simply admire it from the ground, the Eiffel Tower is an unmistakable symbol of Paris. <br> <br> Continuing our tour, we enter the charming neighborhood of Montmartre, known for its bohemian atmosphere and picturesque beauty. Explore its narrow cobbled streets and arrive at the imposing Basilica of the Sacred Heart, which offers panoramic views of the city. Don't forget to visit the famous Moulin Rouge cabaret and enjoy a show full of energy and glamor. <br> <br> The next destination is the Louvre, one of the largest and most famous museums in the world. Admire masterpieces like the Mona Lisa and the Venus de Milo, as you marvel at the grandeur of the Louvre Palace, an architectural gem in its own right. Visiting its galleries is immersing yourself in the history of art and culture. <br> <br> Crossing the River Seine brings us to the charming neighborhood of Saint-Germain-des-Prés, known for its bookstores, historic cafes, and intellectual atmosphere. Immerse yourself in Parisian culture while enjoying a coffee at the famous Café de Flore or exploring the area's fashion shops and art galleries. <br> <br> The charm of Paris extends to its exquisite gardens. The Jardin du Luxembourg and the Jardin des Tuileries are oases of peace and beauty, where you can relax and enjoy the serenity in the midst of the bustling city. Take a romantic walk along its flower-lined paths or enjoy a quiet picnic under the shade of the trees. <br> <br> You cannot visit Paris without exploring the enchanting Île de la Cité, home to the famous Notre Dame Cathedral. This Gothic masterpiece, with its impressive architecture and beautiful stained glass windows, will take you back in time. Although the cathedral suffered a fire in 2019, its grandeur remains captivating and its reconstruction is underway. <br> <br> In short, Paris is a city that envelops you with its elegance, culture and romance. From its iconic monuments to its charming neighborhoods, the French capital offers a unique experience steeped in history and charm."
}

const london = {
    title: 'London: Discover the magic of the City of the Thames',
    price : 'Promotional price of: $600',
    subtitle: 'Immerse yourself in the history, diversity and energy of the British capital',
    paragraph: "Welcome to London, a vibrant city that blends its rich history with a diverse contemporary scene. Known as the City of the Thames, London will captivate you with its charm, its cultural heritage and its cosmopolitan spirit. <br> <br> Our tour of London begins at the iconic Buckingham Palace, the official residence of the Queen of England. If you are lucky, you will be able to witness the changing of the guard, a traditional ceremony full of pomp and colour. From there, you can stroll through the nearby St. James Park and enjoy the serenity of its gardens. <br> <br> Continuing our journey, we arrive at the historic heart of London: the Tower of London. This iconic castle bears witness to centuries of history and is home to the British Crown Jewels. Explore its fortified walls and discover the stories of intrigues, betrayals, and mysteries that surround this place. <br> <br> Crossing Tower Bridge, one of the most recognizable symbols of the city, we enter the bustling Southbank. Here you will find a wide range of cultural attractions, such as the Tate Modern, a museum of contemporary art, and the London Eye, a giant Ferris wheel that offers impressive panoramic views of the city. <br> <br> London is also famous for its world-class museums. The British Museum, with its impressive collection of artifacts and antiquities from around the world, is a must-see treasure. You cannot miss the opportunity to visit the Natural History Museum, with its famous dinosaur skeleton and its impressive collection of specimens. <br> <br> If you are passionate about art, the Tate Britain and the National Gallery will delight you with masterpieces by artists such as Turner, Van Gogh and Rembrandt. In addition, theater lovers cannot miss the famous West End, the district of musicals and plays, where you will find world-renowned shows. <br> <br> London is known for its diversity and multicultural atmosphere. Explore the neighborhoods of Camden Town and Notting Hill, where you will find street markets, vintage shops and a wide range of international cuisine. Don't forget to try the famous British fish and chips, enjoy a high tea in a traditional tea house and visit the charming London pubs. <br> <br> In short, London is a city that combines history, culture and modernity in a unique way. From its iconic landmarks to its vibrant neighborhoods, the British capital invites you to discover its magic and immerse yourself in its contagious energy. Explore London and let yourself be carried away by its fascinating charm!"
}

export {
    barcelona,
    roma,
    paris,
    london
};

// const { barcelona, roma, paris, londres } = require('./ciudades');

//ES6
// export { objeto1, objeto2 };
//import { objeto1, objeto2 } from './ciudades';
